service: two_rivers_reporter
image: andrerobitaille/two_rivers_reporter

servers:
  web:
    - 178.156.250.235

proxy:
  ssl: true
  host: tworiversmatters.com

registry:
  server: ghcr.io
  username: AndreRobitaille
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - TWO_RIVERS_REPORTER_DATABASE_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true
    DB_HOST: two_rivers_reporter-db
    WEB_CONCURRENCY: 2
    RAILS_LOG_LEVEL: info

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "two_rivers_reporter_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

accessories:
  db:
    image: pgvector/pgvector:pg17
    host: 178.156.250.235
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_DB: two_rivers_reporter_production
        POSTGRES_USER: two_rivers_reporter
      secret:
        - POSTGRES_PASSWORD
    files:
      - config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    directories:
      - two_rivers_reporter_pgdata:/var/lib/postgresql/data
