require "test_helper"

class GeneratedImages::GeneratorTest < ActiveSupport::TestCase
  test "creates ready image and attaches generated bytes" do
    meeting = Meeting.create!(detail_page_url: "http://example.com/meeting-image", starts_at: Time.current)
    summary = MeetingSummary.create!(meeting: meeting, summary_type: "minutes_recap", content: "Minutes recap content", generation_data: { "headline" => "Council moved on street repairs", "highlights" => [ { "text" => "Approved a repair plan" } ], "item_details" => [ { "summary" => "Discussed the street repair timeline" } ] })

    ai_service = Minitest::Mock.new
    ai_service.expect(:build_generated_image_brief, { "civic_issue" => "Street repairs", "composition" => "A street repair scene", "avoid" => [ "logos" ] }) do |args|
      assert_equal "Meeting", args[:imageable_type]
      assert_equal false, args[:composite]
      assert_includes args[:source_text], "Council moved on street repairs"
    end
    ai_service.expect(:generate_civic_image, { bytes: "image-bytes", revised_prompt: "revised", model: "gpt-image-1", size: "1536x1024", format: "jpeg" }) do |args|
      assert_match(/realistic local newspaper editorial photograph/i, args[:prompt])
      assert_match(/one dominant resident-visible physical anchor/i, args[:prompt])
      assert_match(/no fake readable document text/i, args[:prompt])
      assert_equal "1536x1024", args[:size]
      assert_equal "jpeg", args[:output_format]
    end

    image = GeneratedImages::Generator.new(meeting, source: summary, ai_service: ai_service).call

    assert_predicate image, :ready?
    assert_predicate image.file, :attached?
    assert_equal "image/jpeg", image.file.content_type
    assert_equal "minutes_recap", image.source_generation_tier
    assert_equal GeneratedImages::ContentFingerprint.for_meeting_summary(summary), image.source_content_fingerprint
    assert_equal summary, image.source_summary
    assert_nil image.source_briefing
    assert_equal "revised", image.revised_prompt if image.respond_to?(:revised_prompt)
    ai_service.verify
  end

  test "passes composite flag through from meeting eligibility" do
    meeting = Meeting.create!(detail_page_url: "http://example.com/meeting-composite", starts_at: Time.current)
    summary = MeetingSummary.create!(
      meeting: meeting,
      summary_type: "minutes_recap",
      content: "Legacy fallback content with approval and repair and permit.",
      generation_data: {
        "headline" => "Street repairs approved with permit and funding",
        "highlights" => [ { "text" => "Approved repair plan" }, { "text" => "Authorized permit and funding" } ],
        "item_details" => [ { "summary" => "Detailed repair and permit discussion" } ]
      }
    )
    eligibility = Struct.new(:eligible?, :reason, :primary_text, :composite?).new(true, nil, "text", true)

    ai_service = Minitest::Mock.new
    ai_service.expect(:build_generated_image_brief, { "civic_issue" => "Composite issue", "composition" => "Comp", "avoid" => [] }) do |args|
      assert_equal true, args[:composite]
    end
    ai_service.expect(:generate_civic_image, { bytes: "image-bytes", revised_prompt: nil, model: "gpt-image-1", size: "1536x1024", format: "jpeg" }) do |args|
      assert_match(/realistic local newspaper editorial photograph/i, args[:prompt])
      assert_match(/one dominant resident-visible physical anchor/i, args[:prompt])
      true
    end

    image = GeneratedImages::Generator.new(meeting, source: summary, eligibility: eligibility, ai_service: ai_service).call

    assert_predicate image, :ready?
    ai_service.verify
  end

  test "supersedes prior ready images" do
    topic = Topic.create!(name: "Image Topic", status: "approved")
    briefing = TopicBriefing.create!(topic: topic, headline: "Headline", upcoming_headline: "Next up", editorial_content: "Editorial", record_content: "Record", generation_tier: "full")
    old_image = GeneratedImage.create!(imageable: topic, status: "ready", purpose: "feature_and_og", source_content_fingerprint: "old", generated_at: 1.day.ago)

    ai_service = Minitest::Mock.new
    ai_service.expect(:build_generated_image_brief, { "civic_issue" => "Topic issue", "composition" => "A topic scene", "avoid" => [] }) do |_args|
      true
    end
    ai_service.expect(:generate_civic_image, { bytes: "new-bytes", revised_prompt: nil, model: "gpt-image-1", size: "1536x1024", format: "jpeg" }) do |_args|
      true
    end

    new_image = GeneratedImages::Generator.new(topic, source: briefing, ai_service: ai_service).call

    assert_predicate new_image, :ready?
    assert_equal "superseded", old_image.reload.status
    ai_service.verify
  end

  test "records custom prompt and admin override" do
    topic = Topic.create!(name: "Prompt Topic", status: "approved")
    briefing = TopicBriefing.create!(topic: topic, headline: "Headline", upcoming_headline: "Next", editorial_content: "Editorial", record_content: "Record", generation_tier: "full")

    ai_service = Minitest::Mock.new
    ai_service.expect(:build_generated_image_brief, { "civic_issue" => "Topic issue", "composition" => "A topic scene", "avoid" => [] }) { true }
    ai_service.expect(:generate_civic_image, { bytes: "new-bytes", revised_prompt: nil, model: "gpt-image-1", size: "1536x1024", format: "jpeg" }) { true }

    image = GeneratedImages::Generator.new(topic, source: briefing, custom_prompt: "Make it warmer", ai_service: ai_service).call

    assert_equal "Make it warmer", image.custom_prompt
    assert_predicate image, :admin_override
    ai_service.verify
  end

  test "adds safer composition instruction when retrying" do
    topic = Topic.create!(name: "Retry Topic", status: "approved")
    briefing = TopicBriefing.create!(topic: topic, headline: "Headline", upcoming_headline: "Next", editorial_content: "Editorial", record_content: "Record", generation_tier: "full")
    failed_image = GeneratedImage.create!(imageable: topic, status: "failed", purpose: "feature_and_og")

    ai_service = Minitest::Mock.new
    ai_service.expect(:build_generated_image_brief, { "civic_issue" => "Topic issue", "composition" => "A topic scene", "avoid" => [] }) { true }
    ai_service.expect(:generate_civic_image, { bytes: "new-bytes", revised_prompt: nil, model: "gpt-image-1", size: "1536x1024", format: "jpeg" }) do |args|
      assert_match(/one visible anchor/i, args[:prompt])
      true
    end

    image = GeneratedImages::Generator.new(topic, source: briefing, generated_image: failed_image, retrying_after: failed_image, ai_service: ai_service).call

    assert_predicate image, :ready?
    ai_service.verify
  end

  test "marks failed and increments retry_count on error" do
    meeting = Meeting.create!(detail_page_url: "http://example.com/meeting-fail", starts_at: Time.current)
    summary = MeetingSummary.create!(meeting: meeting, summary_type: "minutes_recap", content: "Minutes recap content", generation_data: { "headline" => "Headline", "highlights" => [], "item_details" => [] })

    ai_service = Minitest::Mock.new
    ai_service.expect(:build_generated_image_brief, { "civic_issue" => "Issue", "composition" => "A civic scene", "avoid" => [] }) { true }
    ai_service.expect(:generate_civic_image, nil) { raise "boom" }

    image = GeneratedImages::Generator.new(meeting, source: summary, ai_service: ai_service).call

    assert_predicate image, :failed?
    assert_equal 1, image.retry_count
    assert_equal "boom", image.failure_reason
    assert_not_nil image.prompt
    assert_not_nil image.visual_brief
    ai_service.verify
  end

  test "re-raises transient network errors" do
    meeting = Meeting.create!(detail_page_url: "http://example.com/meeting-timeout", starts_at: Time.current)
    summary = MeetingSummary.create!(meeting: meeting, summary_type: "minutes_recap", content: "Minutes recap content", generation_data: { "headline" => "Headline", "highlights" => [], "item_details" => [] })

    ai_service = Minitest::Mock.new
    ai_service.expect(:build_generated_image_brief, { "civic_issue" => "Issue", "composition" => "A civic scene", "avoid" => [] }) { true }
    ai_service.expect(:generate_civic_image, nil) { raise Faraday::TimeoutError.new("timeout") }

    assert_raises(Faraday::TimeoutError) do
      GeneratedImages::Generator.new(meeting, source: summary, ai_service: ai_service).call
    end
  end

  test "transient network error marks reservation failed before re-raise" do
    meeting = Meeting.create!(detail_page_url: "http://example.com/meeting-timeout-2", starts_at: Time.current)
    summary = MeetingSummary.create!(meeting: meeting, summary_type: "minutes_recap", content: "Minutes recap content", generation_data: { "headline" => "Headline", "highlights" => [], "item_details" => [] })

    ai_service = Minitest::Mock.new
    ai_service.expect(:build_generated_image_brief, { "civic_issue" => "Issue", "composition" => "A civic scene", "avoid" => [] }) { true }
    ai_service.expect(:generate_civic_image, nil) { raise Net::ReadTimeout.new("timeout") }

    assert_raises(Net::ReadTimeout) do
      GeneratedImages::Generator.new(meeting, source: summary, ai_service: ai_service).call
    end

    image = meeting.generated_images.order(id: :desc).first
    assert_equal "failed", image.reload.status
    assert_match(/timeout/, image.failure_reason)
    assert_equal 1, image.retry_count
    assert_not_equal "processing", image.status
  end

  test "transient network error updates the existing reservation row" do
    meeting = Meeting.create!(detail_page_url: "http://example.com/meeting-timeout-3", starts_at: Time.current)
    summary = MeetingSummary.create!(meeting: meeting, summary_type: "minutes_recap", content: "Minutes recap content", generation_data: { "headline" => "Headline", "highlights" => [], "item_details" => [] })
    reservation = meeting.generated_images.create!(status: "processing", purpose: "feature_and_og", source_summary: summary, source_generation_tier: "minutes_recap", source_content_fingerprint: GeneratedImages::ContentFingerprint.for_meeting_summary(summary), requested_size: "1536x1024", output_format: "jpeg")

    ai_service = Minitest::Mock.new
    ai_service.expect(:build_generated_image_brief, { "civic_issue" => "Issue", "composition" => "A civic scene", "avoid" => [] }) { true }
    ai_service.expect(:generate_civic_image, nil) { raise Faraday::ConnectionFailed.new("conn failed") }

    assert_raises(Faraday::ConnectionFailed) do
      GeneratedImages::Generator.new(meeting, source: summary, generated_image: reservation, ai_service: ai_service).call
    end

    assert_equal "failed", reservation.reload.status
    assert_equal 1, reservation.retry_count
    assert_match(/conn failed/, reservation.failure_reason)
  end
end
